"""Generate the wrong-turn classification sheet from a traced run.

Failures = official-protocol mismatches. The sheet's analysis columns
(wrong_turn / error_class / subcategory / fix_idea) are INTENTIONALLY empty —
they are filled by humans reading the traces (see traces_report_full.html,
generated by scripts/render_traces.py). Categories:
  KNOWLEDGE   model lacked a fact          -> offline mining fix
  REASONING   had the facts, misused them  -> scaffold/reasoning fix
  GOLD_NOISE  benchmark's gold is defective -> document, not fixable

Usage:
  python scripts/make_classification_sheet.py \
    --results results/bird_traced_rhigh_500.json \
    --out transcripts/rhigh_500/classification_sheet.csv \
    --assignees Aziz Hanyan
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path


def norm(a):
    if a is None:
        return None
    return frozenset(tuple(str(v) for v in row) for row in a)


def official(x) -> bool:
    return (x.get("predicted_answer") is not None
            and x.get("gold_answer") is not None
            and norm(x["predicted_answer"]) == norm(x["gold_answer"]))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--assignees", nargs="+", default=["Aziz", "Hanyan"])
    args = ap.parse_args()

    results = json.loads(Path(args.results).read_text())
    fails = sorted((x for x in results if not official(x)), key=lambda x: x["id"])
    n, k = len(fails), len(args.assignees)
    rows = []
    for i, x in enumerate(fails):
        rows.append({
            "id": x["id"], "db_id": x["db_id"], "difficulty": x.get("difficulty", ""),
            "assignee": args.assignees[min(i * k // n, k - 1)],
            "wrong_turn": "", "error_class": "", "subcategory": "",
            "fix_idea": "", "notes": "",
        })
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=rows[0].keys())
        w.writeheader()
        w.writerows(rows)
    print(f"{n} failures -> {out} (split: {[r['assignee'] for r in rows].count(args.assignees[0])}"
          f"/{n - [r['assignee'] for r in rows].count(args.assignees[0])})")


if __name__ == "__main__":
    main()
